[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.28"
optimize = true
optimizer_runs = 2000000000
ffi = true

# Used to ignore selfdestruct warning
ignored_warnings_from = [
    "test/execution/foreignCalls/foreignCallsEdgeCases.t.sol",
]

remappings = [
    "@openzeppelin/=dependencies/@openzeppelin-contracts-5.3.0/",
    "diamond-std/=lib/diamond-std/",
    "forge-std/=dependencies/forge-std-1.9.7/",
]

# Fork testing configuration
[profile.fork]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.28"
optimize = true
optimizer_runs = 2000000000
ffi = true
fork_url = "${ETHEREUM_RPC_KEY}"

# Coverage testing configuration with via-IR to avoid stack too deep errors
[profile.coverage]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.28"
optimize = true
optimizer_runs = 2000000000
ffi = true
via_ir = true

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_prefix = ""
remappings_location = "config"
recursive_deps = false

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
