name: Contract Size

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Contract Size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and Test
        id: build-and-test
        uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/contract-size@INF-264-On-Chain-Contract-Size
