name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/workflows/onchain-build-test-report.yaml@staging
    secrets: inherit
