name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        id: install-foundry
        uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/install-foundry@staging
      - name: Build and Test
        id: build-and-test
        uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/onchain-build-and-test@staging
        with:
          alchemy_eth_api: ${{ secrets.ALCHEMY_KEY }}
      - name: Contract Size
        id: contract-size
        uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/actions/contract-size@staging